import Head from "next/head";
import Sidenav from "../components/Sidenav";
import MoreAboutMe from "../components/MoreAboutMe";
import ThingsISpendTimeOn from "../components/thingsISpendTimeOn/ThingsISpendTimeOn";
import Landing from "../components/Landing";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Seb Men</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidenav />

      <div className="ml-20 flex justify-center">
        <main className="w-full max-w-[1000px]">
          <Landing />
          <ThingsISpendTimeOn />
          <MoreAboutMe />
        </main>
      </div>
    </div>
  );
}
