import Head from "next/head";
import Sidenav from "../components/Sidenav";
import MoreAboutMe from "../components/MoreAboutMe";
import ThingsISpendTimeOn from "../components/thingsISpendTimeOn/ThingsISpendTimeOn";
import Landing from "../components/Landing";
import SidenavMobile from "../components/SidenavMobile";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Seb Men</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SidenavMobile />
      <Sidenav />

      <div className="flex justify-center  lg:ml-20">
        <main className="w-screen max-w-[1000px] lg:w-full">
          <Landing />
          <ThingsISpendTimeOn />
          <MoreAboutMe />
        </main>
      </div>
    </div>
  );
}
