import Head from "next/head";
import Sidenav from "../components/Sidenav";
import MoreAboutMe from "../components/MoreAboutMe";
import ThingsISpendTimeOn from "../components/thingsISpendTimeOn/ThingsISpendTimeOn";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Seb Men</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidenav />
      <div className="ml-20 flex justify-center">
        <main className="w-full max-w-[1000px] border-2">
          <div className="flex h-screen justify-center">
            <h1 className="mt-64 text-center text-5xl">Page 1</h1>
          </div>
          <ThingsISpendTimeOn />
          <MoreAboutMe />
        </main>
      </div>
    </div>
  );
}
