import React from "react";
import { libraryData } from "../data/librarySummary";
import BackButton from "../components/library/BackButton";
import { Shelf } from "../components/library/Shelf";
import LibraryEasterEgg from "../components/library/LibraryEasterEgg";
import Head from "next/head";

function Library() {
  return (
    <div className="mx-8 mb-32 lg:mx-32">
      <Head>
        <title>My Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LibraryEasterEgg />
      <BackButton />
      <div className="mt-10 lg:ml-32">
        <h1 className="font-title text-5xl font-bold">my library</h1>
        {libraryData.map((row, i) => (
          <Shelf
            key={i}
            year={row.year}
            booksRead={row.booksRead}
            booksInProgress={row.booksInProgress}
          />
        ))}
      </div>
    </div>
  );
}

export default Library;
